sudo: required

script:
  - docker build -t $DOCKER_USER/infycre:${TRAVIS_COMMIT::7}
    docker login --username $DOCKER_USER --password $DOCKER_PASSWORD && docker push $DOCKER_USER/infycre:${TRAVIS_COMMIT::7}
    echo "New image name" $DOCKER_USER/infycre:${TRAVIS_COMMIT::7}
    git config --global user.name $GIT_USER && git config --global user.email $GIT_EMAIL
    git clone https://$GIT_USER:$GIT_PASSWORD@github.com/HiIamLala/infycre-argocd.git && cd infycre-argocd
    kustomize edit set image $DOCKER_USER/infycre:${TRAVIS_COMMIT::7}
    git commit -am "Publish new version" && git push || echo "no changes"