sudo: required


jobs:
  include:
    - stage: build
      script: docker build -t $DOCKER_USER/infycre:${TRAVIS_COMMIT::7} .
      after_script: docker image list && docker login --username $DOCKER_USER --password $DOCKER_PASSWORD && echo "New image name" $DOCKER_USER/infycre:${TRAVIS_COMMIT::7} && docker push $DOCKER_USER/infycre:${TRAVIS_COMMIT::7}
    - stage: deploy
      before_script: curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash && chmod +x kustomize && sudo cp kustomize /usr/bin && kustomize version
      script: git config --global user.name $GIT_USER && git config --global user.email $GIT_EMAIL && git clone https://$GIT_USER:$GIT_PASSWORD@github.com/HiIamLala/infycre-argocd.git && cd infycre-argocd && kustomize edit set image $DOCKER_USER/infycre:${TRAVIS_COMMIT::7}
      after_script: git commit -am "Publish new version" && git push || echo "no changes"